apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: opendeploy-demo
  namespace: default
spec:
  scaleTargetRef:
    name: opendeploy-demo
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 60
  pollingInterval: 10
  triggers:
    - type: cpu
      metadata:
        value: "70"
